allowBuilds:
  '@prisma/client': true
  better-sqlite3: true
  esbuild: true
  sharp: true
  workerd: true
onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - workerd
  - sharp
  - esbuild
packages:
  - '.'
storeDir: /media/z/projects/.pnpm-store/v11
